#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssadmin
    username: ssadmin
    password: ssadmin

#jwt
jwt:
  secret: gx4SN/4gh6QPvLfVWCW8Aoo4l2n66d2338IwXyu1koDT1W94XS35OZJPYkA2IIMMgmlz96LCHSNc8jLYuzwB1IreKOZz2TZhsWODfjHAS9bYlduniCUSuSPZ5/OP15O63fn1kN1N5w64frpyWcWbTtiCgLMkJpnfjmqFMAr7fgcOGyt2rmunvFYni9T78Q4fn/0gpx3qm8zXw3oBbFb1Ge9Wnh1UCSapXd/EzLau3iaXqp9f+8FHmSCo9vbEaRSRMPHdcpnB4WKHKySE/BCNSsWM+kHmHyrAbvKErPCz2XXMnIalUoAtquq03LnmYjrBHyI230VcYEVzGmzLOTsSJw==
  access_token:
    expiration: 3600 # in seconds
  refresh_token:
    expiration: 604800 # in seconds

#是否开启 swagger-ui

knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "这是API文档"
    email: 384704@qq.com
    concat: 张老师
    version: v4.0
    group:
      test1:
        group-name: ssadmin
        api-rule: package
        api-rule-resources:
          - edu.ssadmin


# 日志文件配置


ssadmin:
  captcha:
    enable: false # 开发环境，暂时关闭验证码，方便登录等接口的测试；