server:
  port: 28080

spring:
  application:
    name: ssadmin-server
  profiles:
    active: dev

  main:
    allow-circular-references: true # 允许循环依赖

  jackson:
    #日期格式化

    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
      write-dates-as-timestamps: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true

mybatis:
  mapper-locations: classpath:mappers/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"  # 暴露所有的Actuator端点
  endpoint:
    metrics:
      enabled: true  # 启用metrics端点
  metrics:
    export:
      prometheus:
        enabled: true  # 启用Prometheus度量指标导出

ssadmin:
  info:
    version: 1.0.0
  captcha: # 验证码的开关
    enable: true # 默认为 true

  tenant: # 多租户配置
    enable: false

debug: true