version: "3.4"

services:
  mysql:
    container_name: ssadmin-mysql
    image: mysql:8
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-root}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
    volumes:
      - mysql:/var/lib/mysql/
      - ./sql/ssadmin_init.sql:/docker-entrypoint-initdb.d/ssadmin_init.sql:ro
  
  redis:
    container_name: ssadmin-redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  server:
    container_name: ssadmin-server
    build:
      context: ./ssadmin-server/
      dockerfile: Dockerfile-skywalking # 指定 Dockerfile 的文件名
    image: ssadmin-server
    restart: unless-stopped
    ports:
      - "28080:28080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      JAVA_OPTS: >-
        ${JAVA_OPTS:-}
        -javaagent:/app/skywalking-agent/skywalking-agent.jar
        -Dskywalking.agent.service_name=ssadmin-server
        -Dskywalking.collector.backend_service=skywalking-oap:11800
        -Xms512m
        -Xmx512m
        -Djava.security.egd=file:/dev/./urandom
      ARGS:
        --spring.datasource.url=${DATASOURCE_URL:-jdbc:mysql://ssadmin-mysql:3306/ssadmin?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true}
        --spring.datasource.username=${DATASOURCE_USERNAME:-root}
        --spring.datasource.password=${DATASOURCE_PASSWORD:-123456}
        --spring.redis.host=${REDIS_HOST:-ssadmin-redis}
    depends_on:
      - mysql
      - redis
      - skywalking-oap

  web:
    container_name: ssadmin-web
    build:
      context: ./ssadmin-web
      args:
        NODE_ENV:
          ENV=${NODE_ENV:-production}
          VUE_APP_TITLE=${VUE_APP_TITLE:-SSADMIN管理系统}
    image: ssadmin-web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - server

  skywalking-oap:
    image: apache/skywalking-oap-server:latest # 使用最新版 SkyWalking OAP
    container_name: skywalking-oap
    ports:
      - "11800:11800" # gRPC 端口
      - "12800:12800" # HTTP 端口
    networks:
      - skynet

  skywalking-ui:
    image: apache/skywalking-ui:latest # 使用最新版 SkyWalking UI
    container_name: skywalking-ui
    ports:
      - "8080:8080" # UI 端口
    depends_on:
      - skywalking-oap
    networks:
      - skynet

networks:
  skynet: # 定义一个网络供 SkyWalking 使用

volumes:
  mysql:
    driver: local
  redis:
    driver: local
